# reference: https://dart.dev/tools/pub/automated-publishing
name: Publish to pub.dev

on:
  # pull_request:
  #   branches: [main]
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  pull-requests: write
  id-token: write

jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
