# reference: https://dart.dev/tools/pub/automated-publishing
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    if: ${{ github.repository_owner == 'ReiRev' }}
    permissions:
      id-token: write
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      use-flutter: true
