# reference: https://dart.dev/tools/pub/automated-publishing
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

# jobs:
#   publish:
#     if: ${{ github.repository_owner == 'ReiRev' }}
#     permissions:
#       id-token: write
#       pull-requests: write
#     uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
#     with:
#       use-flutter: true

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # setup OIDC token
      - uses: dart-lang/setup-dart@v1
      # https://github.com/dart-lang/setup-dart/blob/v1/.github/workflows/publish.yml
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: flutter pub publish --force
